### ISSUE TITLE
Notebook for experiments cannot be opened

### ISSUE THREAD

**Issue by NelsonJQ** [arthurlorenzi/copilot-for-linguists#1]
It looks like the jupiter notebook cannot be opened.
Is it only my case?
https://github.com/arthurlorenzi/copilot-for-linguists/blob/main/copilot%20experiment.ipynb

**Comment by arthurlorenzi** [comment]
Hi @NelsonJQ , my bad.

I had incorrectly merged some changes. You should be able to see it now. I hope you find it useful! 

Just a clarification: the FrameNet data is not in this repo. So the part where the data is loaded to generate prompts might not be that useful to you.

Cheers
